services:
  app:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile.front
      args:
        NODE_ENV: ${NODE_ENV}
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
        NEXT_PUBLIC_BASE_PATH: ${NEXT_PUBLIC_BASE_PATH}
        NEXT_PUBLIC_NEXTAUTH_URL: ${NEXT_PUBLIC_NEXTAUTH_URL}
        AUTH_URL: ${AUTH_URL}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    container_name: kvphil-app
    env_file:
      - .env
    networks:
      - frontend
      - backend
    ports:
      - "3010:3000"

  backend:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: kvphil-backend
    network_mode: service:vpn
    depends_on:
      vpn:
        condition: service_healthy
    env_file:
      - .env
    command: >
      sh -c '
      echo "Waiting for VPN service to be fully ready..."
      sleep 15 &&
      echo "Starting FastAPI application..." &&
      uvicorn backend.main:app --host 0.0.0.0 --port 8080 --workers 4
      '

  vpn:
    image: ghcr.io/bubuntux/nordvpn
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - TOKEN=${NORDVPN_TOKEN}
      - CONNECT=Taiwan
      - TECHNOLOGY=NordLynx
      - DNS=1.1.1.1,8.8.8.8 # Set DNS through environment
      - NETWORK=192.168.1.0/24
      - WHITELIST=192.168.1.0/24,172.16.0.0/12
    ports:
      - "8080:8080"
    networks:
      backend:
        aliases:
          - vpn-host
      frontend:
        aliases:
          - vpn-host
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.disable_ipv6=1
    restart: unless-stopped
    volumes:
      - /lib/modules:/lib/modules:ro
    healthcheck:
      test:
        ["CMD-SHELL", "nordvpn status | grep -q 'Status: Connected' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  frontend:
    driver: bridge
  backend:
    name: kvphil_backend
    driver: bridge
