services:
  app:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile.front
      args:
        NODE_ENV: ${NODE_ENV}
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
        NEXT_PUBLIC_BASE_PATH: ${NEXT_PUBLIC_BASE_PATH}
        NEXT_PUBLIC_NEXTAUTH_URL: ${NEXT_PUBLIC_NEXTAUTH_URL}
        AUTH_URL: ${AUTH_URL}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    container_name: kvphil-app
    env_file:
      - .env
    networks:
      - frontend
      - backend
      - myhome-network
    ports:
      - "3010:3000"

  backend:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: kvphil-backend
    env_file:
      - .env
    networks:
      - frontend
      - backend
      - myhome-network
    ports:
      - "8080:8080"
    command: >
      sh -c '
      echo "Starting FastAPI application..." &&
      uvicorn backend.main:app --host 0.0.0.0 --port 8080 --workers 4
      '

networks:
  frontend:
    driver: bridge
  backend:
    name: kvphil_backend
    driver: bridge
  myhome-network:
    external: true
    name: myhome-network
